# A generic, single database configuration.

[alembic]
# Path to migration scripts
script_location = alembic

# Template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# Prepend sys.path with current working directory
prepend_sys_path = .

# Timezone for revision dates
timezone = UTC

# Max length of characters for slug
truncate_slug_length = 40

# Set to 'true' to run the environment during the 'revision' command
revision_environment = false

# Set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions
sourceless = false

# Version location specification; This defaults
# to alembic/versions.
version_locations = alembic/versions

# The output encoding used when revisions are generated
output_encoding = utf-8

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
